name: qyre
description: Qyre screen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  fonts:
    - family: Matter
      fonts:
        - asset: assets/fonts/Matter-Light.otf
          weight: 400
        - asset: assets/fonts/Matter-Medium.otf
          weight: 600
        - asset: assets/fonts/Matter-Bold.otf
          weight: 700

  uses-material-design: true
