name: media
description: Media screen.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Matter
      fonts:
        - asset: assets/fonts/Matter-Light.otf
          weight: 400
        - asset: assets/fonts/Matter-Medium.otf
          weight: 600
        - asset: assets/fonts/Matter-Bold.otf
          weight: 700

  uses-material-design: true
